### PR TITLE
typo: Updating doc to match github config field name

### PR DESCRIPTION
**Pull request by danielacnv**
As per current code label https://github.com/Canva/terraform-provider-buildkite/blob/ab94670a3f7ba016ae3172559d0419a17a73172e/buildkite/provider/resource_pipeline.go#L193

### CODE REVIEW

**Comment by danielacnv** [comment]
This is just for future reference. It seems a typo from the original forked repo.

**Review by olebedev — COMMENTED** [review]
Not sure if we need to maintain the fork separately. Maybe try to send a PR to the original repo and then rebase our fork on the top of its HEAD, WDYT?

**Comment by danielacnv** [comment]
> Not sure if we need to maintain the fork separately. Maybe try to send a PR to the original repo and then rebase our fork on the top of its HEAD, WDYT?

Yeah totally agree. I wasn't sure if we are still keeping up to date with the upstream project. 

I will open PR in the original project. Thanks @olebedev !!

**Comment by danielacnv** [comment]
Will open this PR against the upstream project.

**Pull request closed without merging**
